# 底盘控制器配置
sentry_chassis_controller:
  type: sentry_chassis_controller/SentryChassisController
  wheel_track: 0.362
  wheel_base: 0.362
  wheel_radius: 0.0762
  
  # 转向关节PID参数
  pivot_p_gain: 1.0
  pivot_i_gain: 0.0
  pivot_d_gain: 0.0
  pivot_i_max: 0.0
  pivot_i_min: 0.0
  
  # 轮子速度PID参数
  wheel_p_gain: 2.0
  wheel_i_gain: 0.1
  wheel_d_gain: 0.0
  wheel_i_max: 0.0
  wheel_i_min: 0.0

  # 速度、角速度、转角最大值限制
  max_speed: 10
  max_angular: 10
  max_direction: 45 # 单位：度

  # 小车无输入信号停止阈值
  stop_time: 0.5

  # 底盘是否锁住
  # is_forward_lock: true

  # 坐标系配置
  coordinate_mode: false  # false: 底盘坐标系，true: 全局坐标系
  global_frame_id: "odom"
  robot_base_frame_id: "base_link"

  # 驱动和转向模式
  drive_mode: 1   # 可选值: Forward=0, Backward=1, All=2 前驱 后驱 全驱
  turn_mode: 0    # 可选值: Forward=0, Backward=1, All=2, None=3 前转 后转 全转 履带(不转)
  
  # 小陀螺系数控制
  speed_to_rotate: 100

  # 信息打印
  print_expected_speed: true
  print_expected_pivot: false
  print_odom: false
  
  # 里程计发布配置
  publish_odom: true
  publish_tf: true
  odom_frame_id: "odom"
  base_frame_id: "base_link"
  tf_publish_period: 0.05  # 发布TF的周期，单位秒

# 添加 joint_state_controller 配置
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50   # 默认50Hz