# 底盘控制器配置
sentry_chassis_controller:
  type: sentry_chassis_controller/SentryChassisController
  wheel_track: 0.362
  wheel_base: 0.362
  wheel_radius: 0.0762
  
  # 转向关节PID参数
  pivot_p_gain: 1.0
  pivot_i_gain: 0.0
  pivot_d_gain: 0.0
  pivot_i_max: 0.0
  pivot_i_min: 0.0
  
  # 轮子速度PID参数
  wheel_p_gain: 2.0
  wheel_i_gain: 0.1
  wheel_d_gain: 0.0
  wheel_i_max: 0.0
  wheel_i_min: 0.0

  # 速度和转向最大值
  speed: 10
  angular: 10

  # 小车无输入信号停止阈值
  stop_time: 0.5

  # 底盘是否锁住
  is_forward_lock: false

  # 小陀螺系数控制
  speed_to_rotate: 100

  # 信息打印
  print_expected_speed: true
  print_expected_pivot: false
  print_odom: false
  
  # 里程计发布配置
  publish_odom: true
  publish_tf: true
  odom_frame_id: "odom"
  base_frame_id: "base_link"
  tf_publish_period: 0.05  # 发布TF的周期，单位秒

# 添加 joint_state_controller 配置
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50   # 可选，默认50Hz